# -*- coding: utf-8 -*-
"""Copy of Get_contexts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d5YqhZYeuU3gsaOFzU5WjyDzCPn89Qif

**THIS IS A READ-ONLY VERSION, PLASE MAKE A COPY BEFORE YOU WORK ON THIS NOTEBOOK**
"""

import nltk #Libraries that we are going to use
nltk.download('punkt')
import sys

##For opening the files we are going to simply use the file explorer (left bar, file icon). Once we are there:
# 1)Mount our drive 
# 2)Drag and drop there the files we want to analyze

corpusinput= '/content/mexico.txt'  #Corpus that we are using
listofwords= '/content/list.txt'    #List of words/entities that we are interested in
#output = open('/content/results.txt','w')   #A file in which we are goingt to save the results


f=open(corpusinput,'r')
raw=f.read()

tokens = nltk.word_tokenize(raw)
text = nltk.Text(tokens)

####We extract contexts###
f2 = open(listofwords, "r")
for x in f2:	
  
  word=x.replace('\n', '').replace(' ', '')
  print("--",word,"--")
  print("Similar words (words in similar contexts):")
  similares=text.similar(word, 7)  #How many similar words we want to retrieve
	
  text.concordance(word, width=200, lines=20)  #Width controls the size of the context window. Lines the number of results
  print()